"""Database models for AI Agent Platform.

SQLAlchemy models for PostgreSQL with pgvector support.
"""

import uuid
from datetime import datetime
from typing import Optional, List, Dict, Any

from sqlalchemy import (
    create_engine,
    Column,
    String,
    Float,
    Integer,
    Boolean,
    DateTime,
    Text,
    ForeignKey,
    JSON,
    Index,
)
from sqlalchemy.dialects.postgresql import UUID, JSONB, ARRAY
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy.pool import QueuePool

Base = declarative_base()


class AgentState(Base):
    """Store agent runtime state and configuration."""
    __tablename__ = "agent_states"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_id = Column(String(64), unique=True, nullable=False, index=True)
    name = Column(String(255), nullable=False)
    agent_type = Column(String(64), nullable=False)

    # Status
    is_active = Column(Boolean, default=True)
    status = Column(String(32), default="idle")  # idle, running, error, stopped

    # Configuration
    config = Column(JSONB, default={})
    provider_config = Column(JSONB, default={})

    # Runtime state
    last_action = Column(String(255))
    last_action_time = Column(DateTime(timezone=True))
    cycle_count = Column(Integer, default=0)
    error_count = Column(Integer, default=0)

    # Memory references
    short_term_memory_id = Column(UUID(as_uuid=True), ForeignKey("memory_chunks.id"))

    # Timestamps
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    memory_chunks = relationship("MemoryChunk", back_populates="agent")
    signals = relationship("Signal", back_populates="agent")
    trades = relationship("Trade", back_populates="agent")

    __table_args__ = (
        Index("ix_agent_states_status", "status"),
        Index("ix_agent_states_type", "agent_type"),
    )


class MemoryChunk(Base):
    """Store agent memory chunks with vector embeddings."""
    __tablename__ = "memory_chunks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_id = Column(String(64), ForeignKey("agent_states.agent_id"), nullable=False, index=True)

    # Memory content
    content = Column(Text, nullable=False)
    content_type = Column(String(32), default="observation")  # observation, action, thought, result

    # Metadata
    metadata = Column(JSONB, default={})
    importance_score = Column(Float, default=0.5)  # 0-1 scale
    access_count = Column(Integer, default=0)

    # Vector embedding (pgvector)
    # Note: This requires the pgvector extension
    # embedding = Column(Vector(1536))  # Dimension depends on embedding model

    # Context tags
    tags = Column(ARRAY(String), default=[])
    related_chunk_ids = Column(ARRAY(UUID(as_uuid=True)), default=[])

    # Timestamps
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    last_accessed = Column(DateTime(timezone=True))
    expires_at = Column(DateTime(timezone=True))  # For short-term memory

    # Relationships
    agent = relationship("AgentState", back_populates="memory_chunks")

    __table_args__ = (
        Index("ix_memory_chunks_type", "content_type"),
        Index("ix_memory_chunks_created", "created_at"),
        Index("ix_memory_chunks_importance", "importance_score"),
    )


class Signal(Base):
    """Store trading signals generated by agents."""
    __tablename__ = "signals"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Signal source
    agent_id = Column(String(64), ForeignKey("agent_states.agent_id"), nullable=False, index=True)
    strategy_id = Column(String(64), nullable=True, index=True)

    # Signal details
    symbol = Column(String(32), nullable=False, index=True)
    signal_type = Column(String(16), nullable=False)  # BUY, SELL, HOLD, STRONG_BUY, STRONG_SELL
    strength = Column(Integer, nullable=False)  # 1-5
    confidence = Column(Float, nullable=False)  # 0-1

    # Price data
    price_at_signal = Column(Float, nullable=False)
    price_currency = Column(String(8), default="USD")

    # Analysis
    reasoning = Column(Text)
    indicators = Column(JSONB, default={})  # RSI, MACD, Bollinger Bands, etc.
    market_context = Column(JSONB, default={})  # Market conditions at signal time

    # Execution tracking
    executed = Column(Boolean, default=False)
    execution_price = Column(Float)
    execution_time = Column(DateTime(timezone=True))
    pnl_after_execution = Column(Float)  # Profit/loss if executed

    # Timestamps
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow, index=True)
    expires_at = Column(DateTime(timezone=True))  # Signal validity

    # Relationships
    agent = relationship("AgentState", back_populates="signals")

    __table_args__ = (
        Index("ix_signals_symbol_type", "symbol", "signal_type"),
        Index("ix_signals_created", "created_at"),
        Index("ix_signals_executed", "executed"),
    )


class Trade(Base):
    """Store executed trades (paper trading)."""
    __tablename__ = "trades"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    trade_id = Column(String(64), unique=True, nullable=False, index=True)

    # Trade source
    agent_id = Column(String(64), ForeignKey("agent_states.agent_id"), nullable=False)
    strategy_id = Column(String(64), nullable=True)
    signal_id = Column(UUID(as_uuid=True), ForeignKey("signals.id"), nullable=True)

    # Trade details
    symbol = Column(String(32), nullable=False, index=True)
    side = Column(String(8), nullable=False)  # BUY, SELL
    order_type = Column(String(16), nullable=False)  # MARKET, LIMIT, STOP

    # Quantities
    quantity = Column(Float, nullable=False)
    filled_quantity = Column(Float, default=0)

    # Prices
    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float)
    avg_fill_price = Column(Float)

    # Costs
    commission = Column(Float, default=0)
    slippage = Column(Float, default=0)

    # PnL
    realized_pnl = Column(Float)
    realized_pnl_pct = Column(Float)

    # Risk management
    stop_loss = Column(Float)
    take_profit = Column(Float)
    exit_reason = Column(String(32))  # manual, stop_loss, take_profit, signal

    # Status
    status = Column(String(16), default="open")  # open, closed, cancelled

    # Timestamps
    entry_time = Column(DateTime(timezone=True), default=datetime.utcnow)
    exit_time = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    agent = relationship("AgentState", back_populates="trades")

    __table_args__ = (
        Index("ix_trades_symbol_status", "symbol", "status"),
        Index("ix_trades_entry_time", "entry_time"),
        Index("ix_trades_agent", "agent_id"),
    )


class Position(Base):
    """Store current positions (paper trading)."""
    __tablename__ = "positions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    position_id = Column(String(64), unique=True, nullable=False, index=True)

    # Position source
    agent_id = Column(String(64), nullable=False, index=True)
    strategy_id = Column(String(64), nullable=True)

    # Position details
    symbol = Column(String(32), nullable=False, index=True)
    side = Column(String(8), nullable=False)  # LONG, SHORT

    # Entry
    entry_price = Column(Float, nullable=False)
    entry_time = Column(DateTime(timezone=True), default=datetime.utcnow)
    quantity = Column(Float, nullable=False)

    # Current state
    current_price = Column(Float)
    unrealized_pnl = Column(Float, default=0)
    unrealized_pnl_pct = Column(Float, default=0)

    # Risk management
    stop_loss = Column(Float)
    take_profit = Column(Float)

    # Metadata
    trades = Column(JSONB, default=[])  # List of trade IDs
    metadata = Column(JSONB, default={})

    # Status
    is_open = Column(Boolean, default=True, index=True)

    # Timestamps
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)
    closed_at = Column(DateTime(timezone=True))

    __table_args__ = (
        Index("ix_positions_symbol_open", "symbol", "is_open"),
        Index("ix_positions_agent", "agent_id"),
    )


class PortfolioSnapshot(Base):
    """Store periodic portfolio snapshots for performance tracking."""
    __tablename__ = "portfolio_snapshots"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Snapshot data
    total_equity = Column(Float, nullable=False)
    cash = Column(Float, nullable=False)
    positions_value = Column(Float, nullable=False)

    # Performance
    total_return = Column(Float, default=0)
    total_return_pct = Column(Float, default=0)

    # Trade statistics
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    win_rate = Column(Float, default=0)

    # Costs
    total_commissions = Column(Float, default=0)
    total_slippage = Column(Float, default=0)

    # Detailed breakdown
    positions_detail = Column(JSONB, default=[])
    open_orders = Column(JSONB, default=[])

    # Timestamps
    snapshot_time = Column(DateTime(timezone=True), default=datetime.utcnow, index=True)
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)


class StrategyConfiguration(Base):
    """Store trading strategy configurations."""
    __tablename__ = "strategy_configurations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    strategy_id = Column(String(64), unique=True, nullable=False, index=True)

    # Configuration
    name = Column(String(255), nullable=False)
    strategy_type = Column(String(32), nullable=False)  # momentum, mean_reversion, breakout
    symbols = Column(ARRAY(String), nullable=False)

    # Parameters
    parameters = Column(JSONB, default={})
    risk_parameters = Column(JSONB, default={})

    # Status
    is_active = Column(Boolean, default=False)
    is_paused = Column(Boolean, default=False)

    # Timestamps
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)
    activated_at = Column(DateTime(timezone=True))
    deactivated_at = Column(DateTime(timezone=True))

    # Performance tracking
    signals_generated = Column(Integer, default=0)
    trades_executed = Column(Integer, default=0)
    total_pnl = Column(Float, default=0)

    __table_args__ = (
        Index("ix_strategies_type", "strategy_type"),
        Index("ix_strategies_active", "is_active"),
    )


class MarketDataCache(Base):
    """Cache market data to reduce API calls."""
    __tablename__ = "market_data_cache"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Data identification
    symbol = Column(String(32), nullable=False, index=True)
    data_type = Column(String(32), nullable=False)  # ticker, ohlcv, orderbook
    timeframe = Column(String(8), nullable=True)  # 1m, 5m, 1h, 1d

    # Data
    data = Column(JSONB, nullable=False)
    source = Column(String(32), nullable=False)  # coingecko, cryptocompare, dexscreener

    # Cache control
    fetched_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    expires_at = Column(DateTime(timezone=True), nullable=False, index=True)
    access_count = Column(Integer, default=0)

    __table_args__ = (
        Index("ix_market_cache_symbol_type", "symbol", "data_type"),
        Index("ix_market_cache_expires", "expires_at"),
    )


class SystemLog(Base):
    """Store structured system logs."""
    __tablename__ = "system_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Log details
    level = Column(String(16), nullable=False, index=True)  # DEBUG, INFO, WARNING, ERROR, CRITICAL
    component = Column(String(64), nullable=False, index=True)  # agent, strategy, api, telegram
    message = Column(Text, nullable=False)

    # Context
    context = Column(JSONB, default={})
    agent_id = Column(String(64), nullable=True, index=True)
    trace_id = Column(String(64), nullable=True)

    # Source
    source_file = Column(String(255))
    source_line = Column(Integer)

    # Timestamp
    timestamp = Column(DateTime(timezone=True), default=datetime.utcnow, index=True)
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)

    __table_args__ = (
        Index("ix_logs_level_time", "level", "timestamp"),
        Index("ix_logs_component_time", "component", "timestamp"),
    )


# Database connection utilities

def create_database_engine(database_url: str, **kwargs):
    """Create a SQLAlchemy engine with connection pooling."""
    return create_engine(
        database_url,
        poolclass=QueuePool,
        pool_size=kwargs.get('pool_size', 10),
        max_overflow=kwargs.get('max_overflow', 20),
        pool_pre_ping=True,
        pool_recycle=3600,
        echo=kwargs.get('echo', False),
    )


def init_database(engine):
    """Initialize database tables."""
    # Enable pgvector extension
    from sqlalchemy import text
    with engine.connect() as conn:
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))
        conn.commit()

    # Create tables
    Base.metadata.create_all(bind=engine)


def get_session_factory(engine):
    """Get a session factory bound to the engine."""
    return sessionmaker(autocommit=False, autoflush=False, bind=engine)
